@baseUrl = http://localhost:4000/api

# Categories
###
# @name getAllCategories
GET {{baseUrl}}/categories

###============
# @name addNewCategories
POST {{baseUrl}}/categories
Content-Type: application/json

{
    "name": "Laptop 123"
}
###============
# @name updateCategories
PATCH  {{baseUrl}}/categories/89hjPAT
Content-Type: application/json

{
    "name": "Laptop New"
}
###============
# @name removeCategories
DELETE   {{baseUrl}}/categories/HzSVqK-
