@baseUrl = http://localhost:4000/api
@resourceName=products
# Products
###
# @name getAll
GET {{baseUrl}}/{{resourceName}}

###============
# @name filter
GET {{baseUrl}}/{{resourceName}}?color=blue

###============
GET {{baseUrl}}/{{resourceName}}?price_gte=900

###============
# @name like
GET {{baseUrl}}/{{resourceName}}?name_like=ast

###============
# @name pagination
GET {{baseUrl}}/{{resourceName}}?_page=1&_limit=5

###============
# @name sort
GET {{baseUrl}}/{{resourceName}}?_sort=price&_order=asc


###============
# @name addNew
POST {{baseUrl}}/{{resourceName}}
Content-Type: application/json

{
    "name": "Laptop 123"
}
###============
# @name update
PATCH  {{baseUrl}}/{{resourceName}}/1CU-LRI
Content-Type: application/json

{
    "name": "Laptop New"
}
###============
# @name remove
DELETE   {{baseUrl}}/{{resourceName}}/1CU-LRI
